create table if not exists public.staff_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'empleado'))
);

create table if not exists public.pedidos (
  id text primary key,
  folio bigint generated by default as identity unique not null,
  creado timestamptz not null default now(),
  estatus text not null default 'pendiente' check (estatus in ('pendiente', 'proceso', 'terminado')),
  estatus_pago text not null default 'pendiente' check (estatus_pago in ('pendiente', 'pagado')),
  datos jsonb not null,
  cliente_telefono text generated always as (
    case
      when length(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')) = 10
        then '52' || regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')
      when length(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')) = 13
        and left(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g'), 3) = '521'
        then '52' || substring(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g') from 4)
      else regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')
    end
  ) stored
);

alter table public.pedidos add column if not exists estatus_pago text not null default 'pendiente'
  check (estatus_pago in ('pendiente', 'pagado'));

create table if not exists public.pedidos_cliente (
  id text primary key references public.pedidos(id) on delete cascade,
  folio bigint not null,
  cliente_telefono text,
  fecha_entrega text,
  total numeric(12, 2) not null,
  anticipo numeric(12, 2) not null,
  estatus text not null check (estatus in ('pendiente', 'proceso', 'terminado')),
  estatus_pago text not null default 'pendiente' check (estatus_pago in ('pendiente', 'pagado'))
);

alter table public.pedidos_cliente add column if not exists estatus_pago text not null default 'pendiente'
  check (estatus_pago in ('pendiente', 'pagado'));

create index if not exists pedidos_cliente_telefono_idx on public.pedidos (cliente_telefono);
create index if not exists pedidos_cliente_telefono_summary_idx on public.pedidos_cliente (cliente_telefono);

alter table public.staff_roles enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedidos_cliente enable row level security;

revoke all on public.staff_roles from anon;
revoke all on public.pedidos from anon;
revoke all on public.pedidos_cliente from anon;
grant select on public.staff_roles to authenticated;
grant select, insert, update, delete on public.pedidos to authenticated;
grant select on public.pedidos_cliente to authenticated;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.pedidos', 'folio');
  if sequence_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', sequence_name);
  end if;
end;
$$;

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.staff_roles where user_id = auth.uid()
$$;

grant execute on function public.current_staff_role() to authenticated;
revoke all on function public.current_staff_role() from public, anon;

drop policy if exists "Staff can read own role" on public.staff_roles;
create policy "Staff can read own role"
on public.staff_roles for select to authenticated
using (user_id = auth.uid());

drop policy if exists "Staff can read orders" on public.pedidos;
create policy "Staff can read orders"
on public.pedidos for select to authenticated
using (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Customers can read their order summaries" on public.pedidos_cliente;
create policy "Customers can read their order summaries"
on public.pedidos_cliente for select to authenticated
using (
  coalesce(auth.jwt() ->> 'phone', '') <> ''
  and cliente_telefono = regexp_replace(coalesce(auth.jwt() ->> 'phone', ''), '[^0-9]', '', 'g')
);

drop function if exists public.consultar_pedidos_por_telefono(text);
create function public.consultar_pedidos_por_telefono(telefono_buscado text)
returns table (folio bigint, fecha_entrega text, estatus text, estatus_pago text, total numeric, anticipo numeric)
language sql
stable
security definer
set search_path = ''
as $$
  with telefono_normalizado as (
    select regexp_replace(coalesce(telefono_buscado, ''), '[^0-9]', '', 'g') as digitos
  )
  select pedido.folio, pedido.fecha_entrega, pedido.estatus, pedido.estatus_pago, pedido.total, pedido.anticipo
  from public.pedidos_cliente as pedido
  cross join telefono_normalizado
  where pedido.cliente_telefono = case
    when length(telefono_normalizado.digitos) = 10 then '52' || telefono_normalizado.digitos
    when length(telefono_normalizado.digitos) = 13 and left(telefono_normalizado.digitos, 3) = '521'
      then '52' || substring(telefono_normalizado.digitos from 4)
    when length(telefono_normalizado.digitos) = 12 and left(telefono_normalizado.digitos, 2) = '52'
      then telefono_normalizado.digitos
    else ''
  end
  order by pedido.folio desc
  limit 20
$$;

revoke all on function public.consultar_pedidos_por_telefono(text) from public;
grant execute on function public.consultar_pedidos_por_telefono(text) to anon, authenticated;

drop policy if exists "Admins can insert orders" on public.pedidos;
drop policy if exists "Staff can create orders" on public.pedidos;
create policy "Staff can create orders"
on public.pedidos for insert to authenticated
with check (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Staff can update order status" on public.pedidos;
drop policy if exists "Admins can update orders" on public.pedidos;
create policy "Admins can update orders"
on public.pedidos for update to authenticated
using (public.current_staff_role() = 'admin')
with check (public.current_staff_role() = 'admin');

drop function if exists public.actualizar_estatus_pedido(text, text);
create function public.actualizar_estatus_pedido(
  p_pedido_id text,
  p_nuevo_estatus text,
  p_nuevo_estatus_pago text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  pedido_actualizado public.pedidos%rowtype;
  pago_actual text;
begin
  if coalesce(public.current_staff_role(), '') <> 'empleado' then
    raise exception 'Solo un empleado puede usar esta funcion.';
  end if;
  if p_nuevo_estatus not in ('pendiente', 'proceso', 'terminado') then
    raise exception 'Estatus de pedido no valido.';
  end if;
  if p_nuevo_estatus_pago is null or p_nuevo_estatus_pago not in ('pendiente', 'pagado') then
    raise exception 'Estatus de pago no valido.';
  end if;

  select pedido.estatus_pago into pago_actual
  from public.pedidos as pedido
  where pedido.id = p_pedido_id
  for update;
  if not found then
    raise exception 'No se encontro el pedido solicitado.';
  end if;
  if pago_actual = 'pagado' and p_nuevo_estatus_pago <> pago_actual then
    raise exception 'Solo el administrador puede modificar un pago marcado como pagado.';
  end if;

  update public.pedidos as pedido
  set estatus = p_nuevo_estatus,
      estatus_pago = p_nuevo_estatus_pago
  where pedido.id = p_pedido_id
  returning pedido.* into pedido_actualizado;

  if not found then
    raise exception 'No se encontro el pedido solicitado.';
  end if;

  return jsonb_build_object(
    'id', pedido_actualizado.id,
    'folio', pedido_actualizado.folio,
    'creado', pedido_actualizado.creado,
    'estatus', pedido_actualizado.estatus,
    'estatus_pago', pedido_actualizado.estatus_pago,
    'datos', pedido_actualizado.datos
  );
end;
$$;

revoke all on function public.actualizar_estatus_pedido(text, text, text) from public, anon;
grant execute on function public.actualizar_estatus_pedido(text, text, text) to authenticated;

drop policy if exists "Admins can delete orders" on public.pedidos;
create policy "Admins can delete orders"
on public.pedidos for delete to authenticated
using (public.current_staff_role() = 'admin');

drop trigger if exists protect_order_updates on public.pedidos;
drop function if exists public.protect_order_updates();

create or replace function public.sync_customer_order_summary()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  subtotal numeric;
begin
  select coalesce(sum(
    coalesce(nullif(item ->> 'cantidad', '')::numeric, 0)
    * coalesce(nullif(item ->> 'precio', '')::numeric, 0)
  ), 0)
  into subtotal
  from jsonb_array_elements(coalesce(new.datos -> 'productos', '[]'::jsonb)) as products(item);

  insert into public.pedidos_cliente (
    id, folio, cliente_telefono, fecha_entrega, total, anticipo, estatus, estatus_pago
  ) values (
    new.id,
    new.folio,
    new.cliente_telefono,
    new.datos ->> 'fechaEntrega',
    subtotal + case when coalesce((new.datos ->> 'ivaAplica')::boolean, false) then subtotal * 0.16 else 0 end,
    coalesce(nullif(new.datos ->> 'anticipo', '')::numeric, 0),
    new.estatus,
    new.estatus_pago
  )
  on conflict (id) do update set
    folio = excluded.folio,
    cliente_telefono = excluded.cliente_telefono,
    fecha_entrega = excluded.fecha_entrega,
    total = excluded.total,
    anticipo = excluded.anticipo,
    estatus = excluded.estatus,
    estatus_pago = excluded.estatus_pago;
  return new;
end;
$$;

drop trigger if exists sync_customer_order_summary on public.pedidos;
create trigger sync_customer_order_summary
after insert or update on public.pedidos
for each row execute function public.sync_customer_order_summary();
revoke all on function public.sync_customer_order_summary() from public, anon, authenticated;

create or replace function public.sincronizar_folio_pedidos()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  sequence_name text;
  max_folio bigint;
begin
  if coalesce(public.current_staff_role(), '') <> 'admin' then
    raise exception 'Solo un administrador puede sincronizar los folios.';
  end if;
  sequence_name := pg_get_serial_sequence('public.pedidos', 'folio');
  select coalesce(max(folio), 0) into max_folio from public.pedidos;
  if sequence_name is not null then
    if max_folio = 0 then
      perform setval(sequence_name, 1, false);
    else
      perform setval(sequence_name, max_folio, true);
    end if;
  end if;
end;
$$;

grant execute on function public.sincronizar_folio_pedidos() to authenticated;
revoke all on function public.sincronizar_folio_pedidos() from public, anon;
