create table if not exists public.staff_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'empleado'))
);

create table if not exists public.pedidos (
  id text primary key,
  folio bigint generated by default as identity unique not null,
  creado timestamptz not null default now(),
  estatus text not null default 'pendiente' check (estatus in ('pendiente', 'proceso', 'terminado')),
  estatus_pago text not null default 'pendiente' check (estatus_pago in ('pendiente', 'en_proceso', 'pagado')),
  datos jsonb not null,
  cliente_telefono text generated always as (
    case
      when length(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')) = 10
        then '52' || regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')
      when length(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')) = 13
        and left(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g'), 3) = '521'
        then '52' || substring(regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g') from 4)
      else regexp_replace(coalesce(datos #>> '{cliente,whatsapp}', ''), '[^0-9]', '', 'g')
    end
  ) stored
);

alter table public.pedidos add column if not exists estatus_pago text not null default 'pendiente'
  check (estatus_pago in ('pendiente', 'en_proceso', 'pagado'));

alter table public.pedidos add column if not exists revisado boolean not null default false;

create or replace function public.limpiar_revisado_pedido()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.estatus <> 'terminado' or new.estatus_pago <> 'pagado' then
    new.revisado := false;
  end if;
  if new.revisado and coalesce(new.datos ? 'imagenPath', false) then
    raise exception 'No se pueden asociar imagenes a un pedido marcado como revisado.';
  end if;
  return new;
end;
$$;

drop trigger if exists limpiar_revisado_pedido on public.pedidos;
create trigger limpiar_revisado_pedido
before insert or update on public.pedidos
for each row execute function public.limpiar_revisado_pedido();
revoke all on function public.limpiar_revisado_pedido() from public, anon, authenticated;

alter table public.pedidos alter column folio drop identity if exists;

create or replace function public.generar_folio_aleatorio()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  bytes_aleatorios bytea;
  valor_aleatorio bigint;
  folio_candidato bigint;
  indice_byte integer;
begin
  if new.folio between 100000 and 999999
    and not exists (select 1 from public.pedidos as pedido where pedido.folio = new.folio) then
    return new;
  end if;

  loop
    bytes_aleatorios := pg_catalog.uuid_send(pg_catalog.gen_random_uuid());
    valor_aleatorio := 0;
    for indice_byte in 0..7 loop
      valor_aleatorio := (valor_aleatorio * 256 + pg_catalog.get_byte(bytes_aleatorios, indice_byte)) % 900000;
    end loop;
    folio_candidato := 100000 + valor_aleatorio;
    if not exists (select 1 from public.pedidos as pedido where pedido.folio = folio_candidato) then
      new.folio := folio_candidato;
      return new;
    end if;
  end loop;
end;
$$;

drop trigger if exists generar_folio_aleatorio on public.pedidos;
create trigger generar_folio_aleatorio
before insert on public.pedidos
for each row execute function public.generar_folio_aleatorio();
revoke all on function public.generar_folio_aleatorio() from public, anon, authenticated;

create table if not exists public.pedidos_cliente (
  id text primary key references public.pedidos(id) on delete cascade,
  folio bigint not null,
  cliente_telefono text,
  fecha_entrega text,
  total numeric(12, 2) not null,
  anticipo numeric(12, 2) not null,
  estatus text not null check (estatus in ('pendiente', 'proceso', 'terminado')),
  estatus_pago text not null default 'pendiente' check (estatus_pago in ('pendiente', 'en_proceso', 'pagado'))
);

alter table public.pedidos_cliente add column if not exists hora_entrega text;

alter table public.pedidos_cliente add column if not exists estatus_pago text not null default 'pendiente'
  check (estatus_pago in ('pendiente', 'en_proceso', 'pagado'));

alter table public.pedidos drop constraint if exists pedidos_estatus_pago_check;
alter table public.pedidos add constraint pedidos_estatus_pago_check
  check (estatus_pago in ('pendiente', 'en_proceso', 'pagado'));
alter table public.pedidos_cliente drop constraint if exists pedidos_cliente_estatus_pago_check;
alter table public.pedidos_cliente add constraint pedidos_cliente_estatus_pago_check
  check (estatus_pago in ('pendiente', 'en_proceso', 'pagado'));

create index if not exists pedidos_cliente_telefono_idx on public.pedidos (cliente_telefono);
create index if not exists pedidos_cliente_telefono_summary_idx on public.pedidos_cliente (cliente_telefono);

alter table public.staff_roles enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedidos_cliente enable row level security;

revoke all on public.staff_roles from anon;
revoke all on public.pedidos from anon;
revoke all on public.pedidos_cliente from anon;
grant select on public.staff_roles to authenticated;
grant select, insert, update, delete on public.pedidos to authenticated;
grant select on public.pedidos_cliente to authenticated;

do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence('public.pedidos', 'folio');
  if sequence_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', sequence_name);
  end if;
end;
$$;

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.staff_roles where user_id = auth.uid()
$$;

grant execute on function public.current_staff_role() to authenticated;
revoke all on function public.current_staff_role() from public, anon;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'imagenes-pedidos',
  'imagenes-pedidos',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Staff can read order images" on storage.objects;
create policy "Staff can read order images"
on storage.objects for select to authenticated
using (
  bucket_id = 'imagenes-pedidos'
  and public.current_staff_role() in ('admin', 'empleado')
);

drop policy if exists "Staff can upload order images" on storage.objects;
create policy "Staff can upload order images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'imagenes-pedidos'
  and public.current_staff_role() in ('admin', 'empleado')
);

drop policy if exists "Staff can delete order images" on storage.objects;
create policy "Staff can delete order images"
on storage.objects for delete to authenticated
using (
  bucket_id = 'imagenes-pedidos'
  and public.current_staff_role() in ('admin', 'empleado')
);

drop policy if exists "Staff can read own role" on public.staff_roles;
create policy "Staff can read own role"
on public.staff_roles for select to authenticated
using (user_id = auth.uid());

drop policy if exists "Staff can read orders" on public.pedidos;
drop policy if exists "Admins can read orders" on public.pedidos;
create policy "Admins can read orders"
on public.pedidos for select to authenticated
using (public.current_staff_role() = 'admin');

drop function if exists public.pedidos_para_empleado();
drop function if exists public.actualizar_estatus_pedido(text, text, text);
drop function if exists public.actualizar_estatus_pedido(text, text, text, text);
drop function if exists public.actualizar_estatus_pedido(text, text, text, boolean);
drop function if exists public.actualizar_estatus_pedido(text, text, text, text, jsonb);
drop function if exists public.datos_pedido_para_empleado(jsonb, text, text);
drop function if exists public.datos_pedido_para_empleado(jsonb, text);
drop function if exists public.datos_pedido_para_empleado(jsonb);
create function public.datos_pedido_para_empleado(pedido_datos jsonb, pedido_estatus_pago text)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select jsonb_set(
    (
      jsonb_set(
        pedido_datos,
        '{productos}',
        coalesce((
          select jsonb_agg(producto.value - 'precio')
          from jsonb_array_elements(coalesce(pedido_datos -> 'productos', '[]'::jsonb)) as producto(value)
        ), '[]'::jsonb)
      )
      - 'cliente'
      - 'domicilioEntrega'
      - 'facturacion'
      - 'anticipo'
      - 'metodoPago'
      - 'ivaAplica'
      || jsonb_build_object('cliente', jsonb_build_object(
        'nombre', coalesce(pedido_datos #>> '{cliente,nombre}', ''),
        'whatsapp', coalesce(pedido_datos #>> '{cliente,whatsapp}', pedido_datos #>> '{cliente,telefono}', '')
      ))
    ),
    '{saldoPendiente}',
    case
      when pedido_estatus_pago <> 'pagado' then to_jsonb(greatest(
        0,
        round(
          coalesce((
            select sum(
              coalesce(nullif(producto.value ->> 'cantidad', '')::numeric, 0)
              * coalesce(nullif(producto.value ->> 'precio', '')::numeric, 0)
            )
            from jsonb_array_elements(coalesce(pedido_datos -> 'productos', '[]'::jsonb)) as producto(value)
          ), 0)
          * (1 + case when coalesce((pedido_datos ->> 'ivaAplica')::boolean, false) then 0.16 else 0 end)
          - coalesce(nullif(pedido_datos ->> 'anticipo', '')::numeric, 0),
          2
        )
      ))
      else 'null'::jsonb
    end,
    true
  )
$$;

revoke all on function public.datos_pedido_para_empleado(jsonb, text) from public, anon, authenticated;

drop function if exists public.pedidos_para_empleado();
create function public.pedidos_para_empleado()
returns table (id text, folio bigint, creado timestamptz, estatus text, estatus_pago text, revisado boolean, datos jsonb)
language sql
stable
security definer
set search_path = ''
as $$
  select pedido.id, pedido.folio, pedido.creado, pedido.estatus, pedido.estatus_pago, pedido.revisado,
         public.datos_pedido_para_empleado(pedido.datos, pedido.estatus_pago)
  from public.pedidos as pedido
  where public.current_staff_role() = 'empleado'
  order by pedido.folio desc
$$;

revoke all on function public.pedidos_para_empleado() from public, anon;
grant execute on function public.pedidos_para_empleado() to authenticated;

drop policy if exists "Customers can read their order summaries" on public.pedidos_cliente;
create policy "Customers can read their order summaries"
on public.pedidos_cliente for select to authenticated
using (
  coalesce(auth.jwt() ->> 'phone', '') <> ''
  and cliente_telefono = regexp_replace(coalesce(auth.jwt() ->> 'phone', ''), '[^0-9]', '', 'g')
);

drop function if exists public.consultar_pedidos_por_telefono(text);
drop function if exists public.consultar_pedido_por_folio(bigint);
create function public.consultar_pedido_por_folio(folio_buscado bigint)
returns table (folio bigint, fecha_entrega text, hora_entrega text, estatus text, estatus_pago text, total numeric, anticipo numeric)
language sql
stable
security definer
set search_path = ''
as $$
  select pedido.folio, pedido.fecha_entrega, pedido.hora_entrega, pedido.estatus, pedido.estatus_pago,
         case when public.current_staff_role() = 'empleado' then null else pedido.total end,
         case when public.current_staff_role() = 'empleado' then null else pedido.anticipo end
  from public.pedidos_cliente as pedido
  where pedido.folio = folio_buscado
  limit 1
$$;

revoke all on function public.consultar_pedido_por_folio(bigint) from public;
grant execute on function public.consultar_pedido_por_folio(bigint) to anon, authenticated;

drop policy if exists "Admins can insert orders" on public.pedidos;
drop policy if exists "Staff can create orders" on public.pedidos;
create policy "Staff can create orders"
on public.pedidos for insert to authenticated
with check (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Staff can update order status" on public.pedidos;
drop policy if exists "Admins can update orders" on public.pedidos;
create policy "Admins can update orders"
on public.pedidos for update to authenticated
using (public.current_staff_role() = 'admin')
with check (public.current_staff_role() = 'admin');

drop function if exists public.actualizar_estatus_pedido(text, text, text);
drop function if exists public.actualizar_estatus_pedido(text, text, text, text);
drop function if exists public.actualizar_estatus_pedido(text, text, text, boolean);
drop function if exists public.actualizar_estatus_pedido(text, text, text, text, jsonb);
create function public.actualizar_estatus_pedido(
  p_pedido_id text,
  p_nuevo_estatus text,
  p_nuevo_estatus_pago text,
  p_nueva_imagen_path text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  pedido_actualizado public.pedidos%rowtype;
  pago_actual text;
begin
  if coalesce(public.current_staff_role(), '') <> 'empleado' then
    raise exception 'Solo un empleado puede usar esta funcion.';
  end if;
  if p_nuevo_estatus not in ('pendiente', 'proceso', 'terminado') then
    raise exception 'Estatus de pedido no valido.';
  end if;
  if p_nuevo_estatus_pago is null or p_nuevo_estatus_pago not in ('pendiente', 'en_proceso', 'pagado') then
    raise exception 'Estatus de pago no valido.';
  end if;
  if p_nueva_imagen_path is not null
    and left(p_nueva_imagen_path, length(p_pedido_id) + 1) <> (p_pedido_id || '/') then
    raise exception 'La imagen no pertenece al pedido solicitado.';
  end if;

  select pedido.estatus_pago into pago_actual
  from public.pedidos as pedido
  where pedido.id = p_pedido_id
  for update;
  if not found then
    raise exception 'No se encontro el pedido solicitado.';
  end if;
  if pago_actual = 'pagado' and p_nuevo_estatus_pago <> pago_actual then
    raise exception 'Solo el administrador puede modificar un pago marcado como pagado.';
  end if;

  update public.pedidos as pedido
  set estatus = p_nuevo_estatus,
      estatus_pago = p_nuevo_estatus_pago,
      datos = case
        when p_nueva_imagen_path is null then pedido.datos - 'imagenPath'
        else jsonb_set(pedido.datos, '{imagenPath}', to_jsonb(p_nueva_imagen_path), true)
      end
  where pedido.id = p_pedido_id
  returning pedido.* into pedido_actualizado;

  if not found then
    raise exception 'No se encontro el pedido solicitado.';
  end if;

  return jsonb_build_object(
    'id', pedido_actualizado.id,
    'folio', pedido_actualizado.folio,
    'creado', pedido_actualizado.creado,
    'estatus', pedido_actualizado.estatus,
    'estatus_pago', pedido_actualizado.estatus_pago,
    'revisado', pedido_actualizado.revisado,
    'datos', public.datos_pedido_para_empleado(pedido_actualizado.datos, pedido_actualizado.estatus_pago)
  );
end;
$$;

revoke all on function public.actualizar_estatus_pedido(text, text, text, text) from public, anon;
grant execute on function public.actualizar_estatus_pedido(text, text, text, text) to authenticated;

drop function if exists public.marcar_pedido_revisado(text, boolean);
create function public.marcar_pedido_revisado(p_pedido_id text, p_revisado boolean)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  valor_guardado boolean;
begin
  if coalesce(public.current_staff_role(), '') not in ('admin', 'empleado') then
    raise exception 'Solo el personal autorizado puede usar esta funcion.';
  end if;

  update public.pedidos as pedido
  set revisado = coalesce(p_revisado, false),
      datos = case
        when coalesce(p_revisado, false) then pedido.datos - 'imagenPath'
        else pedido.datos
      end
  where pedido.id = p_pedido_id
    and (not coalesce(p_revisado, false) or (pedido.estatus = 'terminado' and pedido.estatus_pago = 'pagado'))
  returning pedido.revisado into valor_guardado;

  if not found then
    raise exception 'Solo se puede palomear un pedido terminado y pagado.';
  end if;
  return valor_guardado;
end;
$$;

revoke all on function public.marcar_pedido_revisado(text, boolean) from public, anon;
grant execute on function public.marcar_pedido_revisado(text, boolean) to authenticated;

drop policy if exists "Admins can delete orders" on public.pedidos;
create policy "Admins can delete orders"
on public.pedidos for delete to authenticated
using (public.current_staff_role() = 'admin');

drop trigger if exists protect_order_updates on public.pedidos;
drop function if exists public.protect_order_updates();

create or replace function public.sync_customer_order_summary()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  subtotal numeric;
begin
  select coalesce(sum(
    coalesce(nullif(item ->> 'cantidad', '')::numeric, 0)
    * coalesce(nullif(item ->> 'precio', '')::numeric, 0)
  ), 0)
  into subtotal
  from jsonb_array_elements(coalesce(new.datos -> 'productos', '[]'::jsonb)) as products(item);

  insert into public.pedidos_cliente (
    id, folio, cliente_telefono, fecha_entrega, hora_entrega, total, anticipo, estatus, estatus_pago
  ) values (
    new.id,
    new.folio,
    new.cliente_telefono,
    new.datos ->> 'fechaEntrega',
    nullif(new.datos ->> 'horaEntrega', ''),
    subtotal + case when coalesce((new.datos ->> 'ivaAplica')::boolean, false) then subtotal * 0.16 else 0 end,
    coalesce(nullif(new.datos ->> 'anticipo', '')::numeric, 0),
    new.estatus,
    new.estatus_pago
  )
  on conflict (id) do update set
    folio = excluded.folio,
    cliente_telefono = excluded.cliente_telefono,
    fecha_entrega = excluded.fecha_entrega,
    hora_entrega = excluded.hora_entrega,
    total = excluded.total,
    anticipo = excluded.anticipo,
    estatus = excluded.estatus,
    estatus_pago = excluded.estatus_pago;
  return new;
end;
$$;

drop trigger if exists sync_customer_order_summary on public.pedidos;
create trigger sync_customer_order_summary
after insert or update on public.pedidos
for each row execute function public.sync_customer_order_summary();
revoke all on function public.sync_customer_order_summary() from public, anon, authenticated;

update public.pedidos_cliente as resumen
set hora_entrega = nullif(pedido.datos ->> 'horaEntrega', '')
from public.pedidos as pedido
where pedido.id = resumen.id
  and resumen.hora_entrega is distinct from nullif(pedido.datos ->> 'horaEntrega', '');

create or replace function public.sincronizar_folio_pedidos()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  sequence_name text;
  max_folio bigint;
begin
  if coalesce(public.current_staff_role(), '') <> 'admin' then
    raise exception 'Solo un administrador puede sincronizar los folios.';
  end if;
  sequence_name := pg_get_serial_sequence('public.pedidos', 'folio');
  select coalesce(max(folio), 0) into max_folio from public.pedidos;
  if sequence_name is not null then
    if max_folio = 0 then
      perform setval(sequence_name, 1, false);
    else
      perform setval(sequence_name, max_folio, true);
    end if;
  end if;
end;
$$;

grant execute on function public.sincronizar_folio_pedidos() to authenticated;
revoke all on function public.sincronizar_folio_pedidos() from public, anon;

create table if not exists public.cotizaciones (
  id text primary key,
  folio bigint not null unique,
  creado timestamptz not null,
  datos jsonb not null
);

create index if not exists cotizaciones_creado_idx on public.cotizaciones (creado desc);

alter table public.cotizaciones enable row level security;
revoke all on public.cotizaciones from anon;
grant select, insert, update, delete on public.cotizaciones to authenticated;

drop policy if exists "Staff can read quotes" on public.cotizaciones;
create policy "Staff can read quotes"
on public.cotizaciones for select to authenticated
using (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Staff can create quotes" on public.cotizaciones;
create policy "Staff can create quotes"
on public.cotizaciones for insert to authenticated
with check (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Staff can update quotes" on public.cotizaciones;
create policy "Staff can update quotes"
on public.cotizaciones for update to authenticated
using (public.current_staff_role() in ('admin', 'empleado'))
with check (public.current_staff_role() in ('admin', 'empleado'));

drop policy if exists "Staff can delete quotes" on public.cotizaciones;
create policy "Staff can delete quotes"
on public.cotizaciones for delete to authenticated
using (public.current_staff_role() in ('admin', 'empleado'));
